Update Pipeline

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -16,18 +16,18 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Install project dependencies
-        run: make install
+        run: make install 2>&1 | tee build.log
 
       - name: Install tooling
         run: | 
           sudo apt-get update
-          sudo apt-get install -y build-essential clang-tools bear
+          sudo apt-get install -y build-essential clang-tools bear 2>&1 | tee build.log
 
       - name: Build project and generate compilation database
-        run: bear --output compile_commands.json -- make clean all
+        run: bear --output compile_commands.json -- make clean all 2>&1 | tee build.log
 
       - name: Copy compilation database to build directory
-        run: mv compile_commands.json build/
+        run: mv compile_commands.json build/ 2>&1 | tee build.log
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
@@ -37,6 +37,14 @@ jobs:
             build/
           retention-days: 1
 
+      - name: Annotate formatting issues
+        run: |
+          if grep -q "error" build.log; then
+            grep "error" build.log | while IFS= read -r line; do
+              echo "::error::$line"
+            done
+          fi
+
   static-analysis-clang-tidy:
     runs-on: ubuntu-latest
     needs: build
@@ -45,12 +53,12 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Install project dependencies
-        run: make install
+        run: make install 2>&1 | tee static-analysis-clang-tidy.log
 
       - name: Install tooling
         run: |
           sudo apt-get update
-          sudo apt-get install -y clang-tidy clang-tools
+          sudo apt-get install -y clang-tidy clang-tools 2>&1 | tee static-analysis-clang-tidy.log
 
       - name: Open compilation database
         uses: actions/download-artifact@v4
@@ -64,7 +72,15 @@ jobs:
           xargs -0 clang-tidy -p build/ \
             --extra-arg=-std=gnu17 \
             -header-filter=src/ \
-            -checks=clang-analyzer-core.*,clang-analyzer-unix.*,bugprone-narrowing-conversions
+            -checks=clang-analyzer-core.*,clang-analyzer-unix.*,bugprone-narrowing-conversions 2>&1 | tee static-analysis-clang-tidy.log
+
+      - name: Annotate formatting issues
+        run: |
+          if grep -q "error" static-analysis-clang-tidy.log; then
+            grep "error" static-analysis-clang-tidy.log | while IFS= read -r line; do
+              echo "::error::$line"
+            done
+          fi
 
   static-analysis-cppcheck:
     runs-on: ubuntu-latest
@@ -74,12 +90,12 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Install project dependencies
-        run: make install
+        run: make install 2>&1 | tee static-analysis-cppcheck.log
 
       - name: Install tooling
         run: |
           sudo apt-get update
-          sudo apt-get install -y cppcheck
+          sudo apt-get install -y cppcheck 2>&1 | tee static-analysis-cppcheck.log
 
       - name: Open compilation database
         uses: actions/download-artifact@v4
@@ -99,7 +115,15 @@ jobs:
             --suppress=syntaxError:src/user-space/core/setup.c \
             --suppress=syntaxError:src/user-space/core/bpf_manager.c \
             --suppress=syntaxError:src/user-space/core/configuration.c \
-            --suppress=unusedFunction
+            --suppress=unusedFunction 2>&1 | tee static-analysis-cppcheck.log
+
+      - name: Annotate formatting issues
+        run: |
+          if grep -q "error" static-analysis-cppcheck.log; then
+            grep "error" static-analysis-cppcheck.log | while IFS= read -r line; do
+              echo "::error::$line"
+            done
+          fi
 
   code-format-clang-format:
     runs-on: ubuntu-latest
@@ -113,9 +137,65 @@ jobs:
       - name: Install tooling
         run: |
           sudo apt-get update
-          sudo apt-get install -y clang-format
+          sudo apt-get install -y clang-format 2>&1 | tee code-format-clang-format.log
 
       - name: Check formatting
         run: |
           clang-format --dry-run --Werror \
-          $(find src -type f \( -name "*.c" -o -name "*.h" \) ! -name "vmlinux.h")
+          $(find src -type f \( -name "*.c" -o -name "*.h" \) ! -name "vmlinux.h") 2>&1 | tee code-format-clang-format.log
+
+      - name: Annotate formatting issues
+        run: |
+          if grep -q "error" code-format-clang-format.log; then
+            grep "error" code-format-clang-format.log | while IFS= read -r line; do
+              echo "::error::$line"
+            done
+          fi
+
+  test:
+    runs-on: ubuntu-latest
+    needs:
+      - static-analysis-clang-tidy
+      - static-analysis-cppcheck
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install project dependencies
+        run: make install 2>&1 | tee test.log
+
+      - name: Install tooling
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jq 2>&1 | tee test.log
+
+      - name: Open compilation database
+        uses: actions/download-artifact@v4
+        with:
+          name: ebpf-packet-loss-emulator
+          path: build/
+
+      - name: Test module loading
+        run: |
+          sudo ./build/bin/ebpf-packet-loss-emulator \
+          --run "list; load --module tc_bernoulli --interface eth0 --attachment-point ingress; exec sleep 10; unload; load -m xdp_bernoulli -i eth0 -a generic; delay 10; exit;" \
+          --dump ./logs/dump.txt 2>&1 | tee test.log
+
+      - name: Confirm module loading
+        run: |
+          if ! grep -q "Module 'tc_bernoulli' attached successfully" ./logs/dump.txt; then
+            echo "error: tc_bernoulli module failed to load"
+            exit 1
+          fi
+          if ! grep -q "Module 'xdp_bernoulli' attached successfully" ./logs/dump.txt; then
+            echo "error: xdp_bernoulli module failed to load"
+            exit 1
+          fi
+
+      - name: Annotate formatting issues
+        run: |
+          if grep -q "error" test.log; then
+            grep "error" test.log | while IFS= read -r line; do
+              echo "::error::$line"
+            done
+          fi
